import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { postsRouter } from "~/server/api/routers/posts";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {data?.map((post) => (
            <div key={post.id}>
              <h1>{post.content}</h1>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
